import { AuthProvider } from "./src/shared/providers/Provider";
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Be_Vietnam_Pro, Roboto } from "next/font/google";
import { TooltipProvider } from "@/components/ui/tooltip";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import { Toaster } from "sonner";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./src/shared/ui/Appsidebar";

const beVietnamPro = Be_Vietnam_Pro({
  weight: "400",
  variable: "--font-beVietnamPro",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: "400",
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Purity UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${roboto.variable} ${beVietnamPro.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* <TooltipProvider>
          
          <SidebarProvider>
            <AppSidebar />
            <main>
              <SidebarTrigger />
              {children}
            </main>
          </SidebarProvider>
          
        </TooltipProvider> */}
        {children}
        <Toaster />
      </body>
    </html>
  );
}
